name: Deploy Frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify github action on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          topic_id: '${{ secrets.TELEGRAM_TOPIC_ID }}'

      - name: Checkout репозитория
        uses: actions/checkout@v4.2.2

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Установка зависимостей
        run: npm install

      - name: Прогон линтера
        run: npm run lint

      - name: Очистка локального dist
        run: rm -rf dist

      - name: Сборка проекта
        run: npm run build

      - name: Очистка папки на сервере
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo rm -rf /var/www/dist/*

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Деплой на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/dist/"
          strip_components: 1
          overwrite: true

      - name: Send Telegram Message
        if: failure()
        env:
          MESSAGE: |
            ❗ Произошла ошибка во время деплоя
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$MESSAGE&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

      - name: Send Telegram Message
        if: success()
        env:
          MESSAGE: |
            ✅ Изменения успешно задеплоены

            🔗 Ссылка на прод 🔗
            ${{ secrets.PRODUCTION_URL || 'Отсутствует' }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$MESSAGE&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"
