name: Deploy Frontend

on: [push]

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Notify github action on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          topic_id: '${{ secrets.TELEGRAM_TOPIC_ID }}'

  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@master

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Cache npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Message
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          MESSAGE: |
            ❗ Произошла ошибка во время установки зависимостей ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}" \
          -d "parse_mode=MarkdownV2"

  lint:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@master

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Restore npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Прогон линтера
        run: npm run lint

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Message
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          MESSAGE: |
            ❗ Произошла ошибка во время прогона линтера ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

  unit-test:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Restore npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Прогон тестов
        run: npm test

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Message
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          MESSAGE: |
            ❗ Произошла ошибка во время прогона юнит тестов ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

  build:
    runs-on: ubuntu-latest
    needs: [ install-cache, lint, unit-test ]
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@master

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Restore npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Создание env файла
        run: |
          touch .env
          echo VITE_SENTRY_SECRET=${{ secrets.SENTRY_SECRET }} >> .env
          echo VITE_SENTRY_URL=${{ secrets.SENTRY_URL }} >> .env
          echo VITE_SENTRY_PROJECT_ID=${{ secrets.SENTRY_PROJECT_ID }} >> .env
          cat .env

      - name: Сборка проекта
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-output
          path: dist
          retention-days: 1

      - name: Upload static artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-output
          path: static
          retention-days: 1

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Message
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          MESSAGE: |
            ❗ Произошла ошибка во время сборки ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

  deployS3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@main
        with:
          name: build-output
          path: static

      - name: Deploy static folder to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: ${{secrets.AWS_S3_ENDPOINT}}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ru-7'
          SOURCE_DIR: 'static'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@main
        with:
          name: build-output
          path: dist

      - name: Очистка папки на сервере
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo rm -rf /home/energet/energet-frontend/dist/*

      - name: Деплой на сервер
        uses: appleboy/scp-action@master
        with:
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist/*
          target: "/home/energet/energet-frontend/dist"
          strip_components: 1
          overwrite: true

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Message
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          MESSAGE: |
            ❗ Произошла ошибка во время деплоя ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"

  notify-success:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram Message
        env:
          MESSAGE: |
            ✅ Изменения успешно задеплоены ✅

            🔗 Ссылка на прод 🔗
            ${{ secrets.PRODUCTION_URL || 'Отсутствует' }}
        run: |
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE" \
          -d "reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"
